### PR TITLE
Shape Drawing Class and Functions

### PR DESCRIPTION
**Pull request by tymefighter**

### CODE REVIEW

**Review by iamrakesh28 — COMMENTED** [review]
1. LineDrawer and CircleDrawer is returning empty lists.
2. Check for multiline comments

**Comment by tymefighter** [comment]
@iamrakesh28 @sakshi1603 I have completed this, can you please take a look

**Comment by tymefighter** [comment]
If you would like to verify the algorithms (or learn more about it) here are the links:

Line Drawing:
 - DDA: 
   [DDA video (preferred)](https://www.youtube.com/watch?v=W5P8GlaEOSI)
   [DDA read](https://www.tutorialspoint.com/computer_graphics/line_generation_algorithm.htm)
 - Bresenham: [Bresenham read](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm)

Circle Drawing
  - Mid Point
    [Mid Point Video (preferred)](https://youtu.be/frrBDwmkQ0E?t=1697)
 
Circle Filling:
   - Mid Point Based: You may discuss with me (I have applied a modified version of Mid Point Algorithm)
   - Devansh Algorithm: You may discuss with Devansh @RathoreDevansh08, he discovered the algorithm

**Comment by iamrakesh28** [comment]
I have reviewed every file except the circle drawing files. The visualizer tool shows the correctness of circle draw algorithm. So, it can be merged.

**Comment by tymefighter** [comment]
@sakshi1603 This can be merged

**Review by iamrakesh28 — APPROVED** [review]

**Pull request merged**
