### PR TITLE
Persistance support

### PR DESCRIPTION
**Pull request by tymefighter**
Add persistence support

### CODE REVIEW

**Comment by tymefighter** [comment]
@iamrakesh28 @sakshi1603  I have completed this one

**Comment by himanshu2047** [comment]
Instead of taking filepath you can take BoardId and save the BoardState in the file named ${BoardId}.txt, in both while saving and loading the state.

**Comment by tymefighter** [comment]
@himanshu2047 That is a good idea !

**Comment by tymefighter** [comment]
But I would choose a better extension...

**Comment by tymefighter** [comment]
@himanshu2047 @iamrakesh28 @sakshi1603 
Can you check once now

**Comment by himanshu2047** [comment]
Change it as per I requested earlier to you.

**Comment by tymefighter** [comment]
@iamrakesh28 @himanshu2047  can you review this ?

**Comment by iamrakesh28** [comment]
This works fine and can be merged..

**Review by iamrakesh28 — APPROVED** [review]

**Comment by himanshu2047** [comment]
@tymefighter can you put this file in processing.server.board

**Pull request merged**
