### PR TITLE
Add equals method for Utility Classes

### PR DESCRIPTION
**Pull request by tymefighter**
Override the Java Object `equals` method for Utility Classes, convict-git/KoraKaagaz#15

### CODE REVIEW

**Review by himanshu2047 — COMMENTED** [review]
Why you are taking type of parameter as object instead of their original type. You are casting it?
It is good if anyone passes any other type of object but is casting is good?

**Comment by tymefighter** [comment]
That is the original method of the Java Object which we must override, hence we cannot change the type

**Review by himanshu2047 — APPROVED** [review]
Nicely written

**Comment by himanshu2047** [comment]
We will also need the comparator function for timestamp, to insert into priority queues.

**Pull request merged**
